name: gossip

services:
  postgres:
    build:
      context: ./infra
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: gossip
      POSTGRES_PASSWORD: gossip
      POSTGRES_DB: gossip_dev
    ports:
      - "5432:5432"
    volumes:
      - gossip_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gossip"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  gossip_pg_data:
